# -*- coding: utf-8 -*-
"""Python Program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7wSjEzIAXu-DKjgZI07gEJ-6PBPTw46
"""

import numpy as np           #Import this library

user_var=int(input("Please input an number between 5 and 15!"))         #ASK for user input

if user_var > 5 and user_var < 15:
  print("The number '" + str(user_var) + "' is an valid number!")               #If input is >5 and <15, prints this, else prints below
else:
  print("The number '" + str(user_var) + "' is invalid!")

randlist=[]                           #Initialize an list var

def myrandom(user_var):               #Create a method
  for i in range(user_var):           #For however many value user inputs
    randlist.append(np.random.randint(10, 50))        #Repeatedly appends to list with random integer between 10 and 50 until value reaches user inputted #
  print(randlist)                                     #Finally, prints out the list with the filled value

def mysum(randlist):        #Creates a method
  total=0                   #Empty variable to store value
  for i in range(0, len(randlist)):   #For each value from 0 to randlist length (which is user inputted #)
    total = total + randlist[i]       #Repeatedly add to previous total every # within randlist until reached end
  print("The sum of the values are: " + str(total))     #Then print out the total

myrandom(user_var)      #Call both method

mysum(randlist)